database:
    driver: sqlite
    databasename: bolt

canonical: tvbands.org
sitename: Tri-Valley Bands
payoff: Impossible is Nothing

theme: tvbands

locale: en_US
timezone: US/Eastern

third_party:
  google_maps_key: "AIzaSyCLGcxVzp7AdIwML6zlzyIKo-avAILtnik"


#
# Maintenance Mode
#

maintenance_mode: false
maintenance_template: maintenance_default.twig

cron_hour: 3

#
# Default Templates
#

homepage_template: index.twig
notfound: notfound.twig
record_template: record.twig
listing_template: listing.twig
listing_records: 6
listing_sort: datepublish DESC

#
# Search & Sort
#
taxonomy_sort: DESC
search_results_template: search.twig
search_results_records: 10
recordsperpage: 10

add_jquery: false

#
# Caching
#

caching:
    config: true
    templates: true
    request: false
    duration: 10
    authenticated: false
    thumbnails: true
    translations: true

changelog:
    enabled: false

thumbnails:
    default_thumbnail: [ 160, 120 ]
    default_image: [ 1000, 750 ]
    quality: 80
    cropping: crop
    notfound_image: view/img/default_notfound.png
    error_image: view/img/default_error.png
    save_files: false
    allow_upscale: false
    exif_orientation: true
    only_aliases: false
#    browser_cache_time: 2592000


#
# HTML Sanitization
#

htmlcleaner:
    allowed_tags: [ div, span, p, br, hr, s, u, strong, em, i, b, li, ul, ol, mark, blockquote, pre, code, tt, h1, h2, h3, h4, h5, h6, dd, dl, dh, table, tbody, thead, tfoot, th, td, tr, a, img, address, abbr, iframe, caption ]
    allowed_attributes: [ id, class, style, name, value, href, src, alt, title, width, height, frameborder, allowfullscreen, scrolling, target, colspan, rowspan ]

#
# Upload handling
#

accept_file_types: [ twig, html, js, css, scss, gif, jpg, jpeg, png, ico, zip, tgz, txt, md, doc, docx, pdf, epub, xls, xlsx, ppt, pptx, mp3, ogg, wav, m4a, mp4, m4v, ogv, wmv, avi, webm, svg]

branding:
     name: "TVBands Admin"
     path: /admin
     provided_by: [ rick@oddlyaccurate.com, "Rick Hutcheson." ]

debug: false
debug_show_loggedoff: false
debug_permission_audit_mode: false
debug_error_level: -1               # equivalent to E_ALL
debug_error_use_symfony: false

#
# System debug logging
#

debuglog:
    enabled: false
    filename: bolt-debug.log
    level: DEBUG


#
# WYSIWYG Options
#

wysiwyg:
    images: false            # Allow users to insert images in the content.
    anchor: true            # Adds a button to create internal anchors to link to.
    tables: false            # Adds a button to insert and modify tables in the content.
    fontcolor: false         # Allow users to mess around with font coloring.
    align: false             # Adds buttons for 'align left', 'align right', etc.
    subsuper: false          # Adds buttons for subscript and superscript, using `<sub>` and `<sup>`.
    embed: false             # Allows the user to insert embedded video's from Youtube, Vimeo, etc.
    underline: false         # Adds a button to underline text, using the `<u>`-tag.
    ruler: false             # Adds a button to add a horizontal ruler, using the `<hr>`-tag.
    strike: false            # Adds a button to add stikethrough, using the `<s>`-tag.
    blockquote: false        # Allows the user to insert blockquotes using the `<blockquote>`-tag.
    codesnippet: false       # Allows the user to insert code snippets using `<pre><code>`-tags.
    specialchar: false       # Adds a button to insert special chars like '€' or '™'.
    ck:
        autoParagraph: true  # If set to 'true', any pasted content is wrapped in `<p>`-tags for multiple line-breaks
        disableNativeSpellChecker: true # If set to 'true' it will stop browsers from underlining spelling mistakes
        allowNbsp: false     # If set to 'false', the editor will strip out `&nbsp;` characters. If set to 'true', it will allow them. ¯\_(ツ)_/¯

# Bolt uses the Google maps API for it's geolocation field and Google now
# requires that it be loaded with an API key on new domains. You can generate
# a key at https://developers.google.com/maps/documentation/javascript/get-api-key
# and enter it here to make sure that the geolocation field works.
# google_api_key:

# Global option to enable/disable the live editor
liveeditor: false

cookies_use_remoteaddr: true
cookies_use_browseragent: false
cookies_use_httphost: true
cookies_lifetime: 1209600
cookies_domain: .tvbands.org

hash_strength: 12

backend:
   news:
       disable: true
