main:
    - label: Home
      path: homepage
      class: first
    - label: Handbook & Forms
      path: documents/
    - label: Events
      path: events/
    - label: Fundraisers
      path: fundraisers/
    - label: Ensembles
      path: ensembles/
    - label: Band Boosters
      path: pages/boosters/
    - label: Musical Links
      path: page/musical-links
    - label: Contact
      path: pages/contact
      class: last
