main:
    - label: Home
      path: homepage
      class: first
    - label: Handbook & Forms
      path: documents/
    - label: Ensembles
      path: ensembles/
    - label: Alumni / Contact
      path: pages/alumni
    - label: Band Boosters
      path: pages/boosters/
    - label: Current Fundraisers
      path: fundraisers/
    - label: Musical Links
      path: links/
      class: last
