# This file defines the different types of taxonomies in Bolt. See the
# documentation for details: https://docs.bolt.cm/contenttypes/taxonomies

#
# Default Taxonomies
#

ensemble_type:
    slug: ensemble-types
    singular_slug: ensemble-types
    behaves_like: grouping
    postfix: "What kind of ensemble is this? (Band, Guard, Drumline, ...)"
    options: { band: "Band", guard: "Guard", drumline: "Drumline", other: "Other (See Ricky if you use this a lot)" }
    has_sortorder: true

tags:
    slug: tags
    singular_slug: tag
    behaves_like: tags
    postfix: "Add some freeform tags. Start a new tag by typing a comma or space."
    allow_spaces: false
    #listing_template: tag-listing.twig #custom template

groups:
    slug: groups
    singular_slug: group
    behaves_like: grouping
    options: { main: "The main group", meta: "Meta group", other: "The other stuff" }
    has_sortorder: true

categories:
    name: Categories
    slug: categories
    singular_name: Category
    singular_slug: category
    behaves_like: categories
    multiple: true
    options: [ news, events, movies, music, books, life, love, fun ]
